sudo: required

services:
  - docker

language: python

before_install:
  - docker pull coedl/kaldi-helpers

script:
  - |
     echo "
          ln -s /test-travis/corpora/abui_toy_corpus /test-travis/input
     " > test.sh
  - cat test.sh
